new loki and promtail packages

diff --git a/packages/golang1.12/packaging b/packages/golang1.12/packaging
--- a/packages/golang1.12/packaging
+++ b/packages/golang1.12/packaging
@@ -1,14 +1,22 @@
 #!/usr/bin/env bash
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
-# abort script on any command that exits with a non zero value
-set -e -x
+# Detect # of CPUs so make jobs can be parallelized
+CPUS=$(grep -c ^processor /proc/cpuinfo)
 
 # Grab the latest versions that are in the directory
-ZLIB_VERSION=$(ls -v -r golang/go*.linux-amd64.tar.gz | sed 's/.*\/go\(.*\)\.tar\.gz$/\1/' | head -1)
-BOSH_PACKAGES_DIR=${BOSH_PACKAGES_DIR:-/var/vcap/packages}
+GOLAN_VERSION=$(ls -r golang/go*.linux-amd64.tar.gz | sed 's/.*\/go\(.*\)\.linux-amd64\.tar\.gz$/\1/' | head -1)
 
+# Available variables
+# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
+# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
+#
+# NOTE: new versions of golang can be found on the official
+#       download page: https://golang.org/dl
+#
+echo "Extracting go ${GOLAN_VERSION} ... "
+tar xzf "golang/go${GOLAN_VERSION}.linux-amd64.tar.gz"
 
-echo "Extracting golang ${GO_VERSION} ... "
-tar xzf golang/go${GO_VERSION}.linux-amd64.tar.gz
+echo "Installing go ..."
 cp -R go/* ${BOSH_INSTALL_TARGET}
-
